import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';

export default function Home() {
  
  const [tasks, addTask] = useState([{title: 'Task 1',body: 'Here is my first task'}]);

  const addTaskHandler = event => {
    event.preventDefault()
    
    addTask([...tasks, { title: '2', body: event.target.task.value }]);

    
  }




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to The Best ToDo Listr
        </h1>
      <label>Submit here your task</label>
      <form onSubmit={addTaskHandler}>
      <label htmlFor="name">Add here a new Task</label>
      <input id="task" type="text" required />
      <button type="submit">Submit</button>
    </form>
      <ul>
      {tasks.map((task) => (
            <li key={task.body}>{task.body}</li>
  ))}
    </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
